### ISSUE TITLE
Waypoint Not Facing my direction

### ISSUE THREAD

**Issue by OriginalTalani** [GitFyu/WaypointsMod#5]
I have a problem, the waypoint that i make is there but it is facing the way im looking wich makes me unable to see it because it should be facing my face than i cansee it but since it is not i can see through it, i figured this out when i looked away from it and turned on my 360 viewing mod.
Please help me and find a way to fix this

**Comment by GitFyu** [comment]
This mod has been abandoned now, I recommend just downloading a more up-to-date waypoints mod
